(define (problem cancercheck_problem)
  (:domain CancerCheck_BNN_2)
  (:init
    (= (total-cost) 0)
    (not (weights-initialized))
    (not (diagnosed))
    (not (test-performed radius_mean))
    (not (test-performed radius_se))
    (not (test-performed radius_worst))
    (not (test-performed area_mean))
    (not (test-performed area_se))
    (not (test-performed area_worst))
    (not (test-performed perimeter_mean))
    (not (test-performed perimeter_se))
    (not (test-performed perimeter_worst))
    (not (test-performed compactness_mean))
    (not (test-performed compactness_se))
    (not (test-performed compactness_worst))
    (has-value radius_mean high)
    (has-value radius_se high)
    (has-value radius_worst low)
    (has-value area_mean high)
    (has-value area_se high)
    (has-value area_worst low)
    (has-value perimeter_mean low)
    (has-value perimeter_se low)
    (has-value perimeter_worst low)
    (has-value compactness_mean low)
    (has-value compactness_se low)
    (has-value compactness_worst low)
  )
  (:goal
    (diagnosed)
  )
  (:metric minimize (total-cost))
)
