(define (problem CancerCheck_BNN_Problem)
  (:domain CancerCheck_BNN)
  (:init
    (= (total-cost) 0)
    (not (weights-initialized))
    (not (diagnosed))
    (not (test-performed radius_mean))
    (not (test-performed radius_se))
    (not (test-performed radius_worst))
    (not (test-performed area_mean))
    (not (test-performed area_se))
    (not (test-performed area_worst))
    (not (test-performed perimeter_mean))
    (not (test-performed perimeter_se))
    (not (test-performed perimeter_worst))
    (not (test-performed compactness_mean))
    (not (test-performed compactness_se))
    (not (test-performed compactness_worst))
    (not (test-performed concavepoints_mean))
    (not (test-performed concavepoints_se))
    (not (test-performed concavepoints_worst))
    (not (test-performed concavity_mean))
    (not (test-performed concavity_se))
    (not (test-performed concavity_worst))
    (not (test-performed fractal_dimension_mean))
    (not (test-performed fractal_dimension_se))
    (not (test-performed fractal_dimension_worst))
    (not (test-performed symmetry_mean))
    (not (test-performed symmetry_se))
    (not (test-performed symmetry_worst))
    (not (test-performed smoothness_mean))
    (not (test-performed smoothness_se))
    (not (test-performed smoothness_worst))  
    (not (test-performed texture_mean))
    (not (test-performed texture_se))
    (not (test-performed texture_worst))

    (has-value radius_mean high)
    (has-value radius_se high)
    (has-value radius_worst low)
    (has-value area_mean high)
    (has-value area_se high)
    (has-value area_worst low)
    (has-value perimeter_mean low)
    (has-value perimeter_se low)
    (has-value perimeter_worst low)
    (has-value compactness_mean low)
    (has-value compactness_se low)
    (has-value compactness_worst low)
    (has-value concavepoints_mean high)
    (has-value concavepoints_se high)
    (has-value concavepoints_worst low)
    (has-value concavity_mean high)
    (has-value concavity_se high)
    (has-value concavity_worst low)
    (has-value fractal_dimension_mean low)
    (has-value fractal_dimension_se low)
    (has-value fractal_dimension_worst low)
    (has-value symmetry_mean low)
    (has-value symmetry_se low)
    (has-value symmetry_worst low)
    (has-value smoothness_mean high)
    (has-value smoothness_se high)
    (has-value smoothness_worst low)
    (has-value texture_mean high)
    (has-value texture_se high)
    (has-value texture_worst low)
  )
  (:goal
    (diagnosed)
  )
  (:metric minimize (total-cost))
)
